version: '3'
services:
  api:
    build:
      context: medresearch
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD="${POSTGRES_PASSWORD}"
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    networks:
      - spring-postgres
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - spring-postgres

volumes:
  data:
networks:
  spring-postgres:
